# Copyright (c) 2026 Realtek Semiconductor Corp.
# SPDX-License-Identifier: Apache-2.0
CONFIG_REALTEK_BEE_PINMUX=y
CONFIG_REALTEK_BEE_RCC=y
CONFIG_REALTEK_BEE_RAP=y
CONFIG_REALTEK_BEE_TIMER=y
CONFIG_REALTEK_BEE_GPIO=y
CONFIG_REALTEK_BEE_DMA=y
CONFIG_REALTEK_BEE_SPI=y
CONFIG_REALTEK_BEE_RTC=y
